### PR TITLE
Weather-App

### PR DESCRIPTION
**Pull request by taiwo2**
Write the functions that hit the API. You’re going to want functions that can take a location and return the weather data for that location. For now, just console.log() the information.
-  Write the functions that process the JSON data you’re getting from the API and return an object with only the data you require for your app.
-  Set up a simple form that will let users input their location and will fetch the weather info (still just console.log() it).
-  Display the information on your webpage!

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @taiwo2, congratulations on this project :muscle: Great job with using the template literals and also using try and catch block in checking the API call :1st_place_medal: Awesome. Let us kindly address the comments below so we can get our project approved

- Kindly implement the toggle functionality so we can toggle between degrees Celcius and Fahrenheit. Currently, we can tell the unit of our temperature
- The appearance of the page must change based on the data retrieved, let us implement this functionality
- Kindly edit the README file so it can reflect the current project. The title and description is obviously different project :+1: 
- Kindly check your linter file against this [file](https://github.com/microverseinc/linters-config/blob/master/javascript/.github/workflows/linters.yml). The linter configuration must be exactly the same
- Kindly take a second look at your README file and check the features and all other sections and make sure it reflects the `Weather App` project

[Optional]
- Let us try to re-structure our files nicely, so we can have files for our API, DOM manipulation, and Logic
- It would be great if we have a loading component that renders until data from the API is returned

Once these are resolved :smile: Kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Changes Requested 💀 

There is always room to improve your code. Your project has met almost all the requirements but I would like to suggest some changes. I hope the next TSE who will review this project would be really impressed if you make those changes. 
- [ ] You have only worked on the Readme after yu received your First Review from Daniel Larbi Addo but there are other changes please work on them too.

When you are done with the changes please request another review. 

_Don't get discouraged. There are some students who make more mistakes than you do. We are here to learn. Everyone from Micrverse is here to help you._ 

**GOOD LUCK!**

In case of any questions, feel free to reach out on slack @arslanbisharat 📞 . 

**Best, 
Arslan Bisharat**

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Taiwo Adetona** 
Good job with the improvements for this project :muscle:  :muscle:
You addressed most of the changes required by the previous code reviewers :clap: :clap: :clap:  
Just one last detail to improve before you can go ahead:

- [ ] The appearance of the page must change based on the data retrieved
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by oloomoses — APPROVED** [review]
# Congratulations, Project Approved. :muscle: :tada: :clap: 
**Great job working on the suggested changes from the previous reviews.
You have passed all the requirements for this project :muscle: 
Feel free to merge and close this pull request.**

**I wish you the best in your next project and see you at the top :rocket:** 
#### Happy Coding
_Slack: Oloo Moses_

**Pull request merged**
